services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template:ro
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
    depends_on:
      - server
      - client
    networks:
      - app-network
    restart: always

  client:
    build:
      context: ./client
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
        - REACT_APP_SOCKET_URL=${REACT_APP_SOCKET_URL}
    container_name: client
    restart: always
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_SOCKET_URL=${REACT_APP_SOCKET_URL}

  server:
    build:
      context: ./server
    container_name: server
    restart: always
    volumes:
      - ./server/uploads:/app/uploads
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_URL=${CLIENT_URL}
      - PORT=${SERVER_PORT}
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: 