services:
  # PostgreSQL база данных
  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
    networks:
      - backend-network

  # Бэкенд Node.js
  backend:
    build: ./server
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      CLIENT_URL: ${DOMAIN_NAME}
      BASE_API_PATH: /api
      SOCKET_PATH: /socket.io
    volumes:
      - ./server/uploads:/app/uploads
    restart: unless-stopped
    networks:
      - backend-network
      - frontend-network

  # Фронтенд React
  frontend:
    build:
      context: ./client
      args:
        - REACT_APP_API_URL=${DOMAIN_NAME}/api
    restart: unless-stopped
    networks:
      - frontend-network

  # Nginx для проксирования
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - frontend-network
      - backend-network

volumes:
  postgres_data:

networks:
  frontend-network:
  backend-network: 